name: pipeline-deploy-s3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc
      - run: pandoc README.md -f markdown -t html -s -o index.html
      - run: ls -la
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}       # Chave de Acesso AWS
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Chave Secreta AWS
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}         # Token de Sessão AWS (credenciais temporárias)
      AWS_EC2_METADATA_DISABLED: true
      BUCKET_S3: my-s3-bucket-name  # Substitua pelo nome do seu bucket S3
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: index.html
      - run: aws s3 cp index.html s3://$BUCKET_S3/index.html --acl public-read  # Faz o upload para o S3